name: CI Desafio Backend Mater Imperium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Step para rodar os testes (Testcontainers subirá o Postgres aqui)
    - name: Run Unit and Integration Tests
      run: mvn test

    # Step para gerar o JAR final
    - name: Build package
      run: mvn -B package -DskipTests

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v1
      with:
        # POM explicitamente
        directory: .